# Site settings
title: "Jared Lincenberg"
email: jaredlincenberg@gmail.com
description: >-
  Interested in nature and programming.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jaredlincenberg.github.io" # the base hostname & protocol for your site

# Author / social links
github_username:  jaredlincenberg
linkedin_username: jared-lincenberg

# Build settings
plugins:
  - jekyll-feed

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
